# Generated by Django 3.2.5 on 2021-12-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('error', 'Erreur'), ('warning', 'Avertissement'), ('info', 'Information')], max_length=10)),
                ('machine', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=8)),
                ('message', models.TextField()),
            ],
        ),
    ]
