# Generated by Django 3.2.5 on 2021-12-08 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(blank=True, max_length=250, null=True)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(max_length=10, unique=True, verbose_name='Tag région')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('oaci', models.CharField(max_length=4, unique=True, verbose_name='Code OACI')),
                ('nom', models.CharField(max_length=124, verbose_name='Nom')),
                ('entete', models.CharField(max_length=11, verbose_name='Entete')),
                ('inseepp', models.CharField(max_length=7, verbose_name='INSEEpp')),
                ('outremer', models.BooleanField(default=False)),
                ('date_pivot', models.DateTimeField(verbose_name="Date changement d'heure")),
                ('ouverture', models.TimeField(verbose_name='H ouverture')),
                ('ouverture_ete', models.TimeField(verbose_name='H ouverture été')),
                ('ouverture_hiver', models.TimeField(verbose_name='H ouverture hiver')),
                ('fermeture', models.TimeField(verbose_name='H fermeture')),
                ('fermeture_ete', models.TimeField(verbose_name='H fermeture été')),
                ('fermeture_hiver', models.TimeField(verbose_name='H fermeture hiver')),
                ('retention', models.IntegerField()),
                ('reconduction', models.IntegerField()),
                ('repousse', models.IntegerField()),
                ('fuseau', models.CharField(max_length=124)),
                ('wind_unit', models.CharField(choices=[('kt', 'kt'), ('kmh', 'km/h')], max_length=3, verbose_name='Unité de vitesse')),
                ('temp_unit', models.CharField(choices=[('c', '°C'), ('f', 'F')], max_length=3, verbose_name='Unité de température')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurateur.region', verbose_name='Dir')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediumSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms', models.CharField(max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurateur.client')),
            ],
        ),
        migrations.CreateModel(
            name='MediumMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurateur.client')),
            ],
        ),
        migrations.CreateModel(
            name='MediumFTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote', models.CharField(max_length=254)),
                ('login', models.CharField(max_length=254)),
                ('pwd', models.CharField(max_length=254)),
                ('dir', models.CharField(blank=True, max_length=254, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurateur.client')),
            ],
        ),
        migrations.CreateModel(
            name='MediumFax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fax', models.CharField(max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurateur.client')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigMAA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('type_maa', models.CharField(choices=[('BLSN', 'BLSN '), ('DENSE_FG', 'Brouillard dense'), ('DS', 'DS '), ('DU', 'DU '), ('FG', 'FG '), ('FWID', 'FWID '), ('FWOID', 'FWOID '), ('FZDZ', 'FZDZ'), ('FZFG', 'FZFG '), ('FZRA', 'FZRA '), ('GR', 'GR '), ('HVY_FZDZ', 'HVY_FZDZ '), ('HVY_FZRA', 'HVY_FZRA '), ('HVY_GR', 'HVY_GR '), ('HVY_SN', 'HVY_SN '), ('HVY_SNRA', 'HVY_SNRA '), ('HVY_SWELL', 'HVY_SWELL'), ('HVY_TS', 'HVY_TS '), ('ICE_DEPOSIT', 'ICE_DEPOSIT '), ('INV_TEMPE', 'INV_TEMPE'), ('RIME', 'RIME '), ('RR1', 'RR1 '), ('RR12', 'RR12 '), ('RR24', 'RR24 '), ('RR3', 'RR3 '), ('RR6', 'RR6 '), ('SA', 'SA '), ('SEA', 'SEA '), ('SN', 'SN'), ('SNRA', 'SNRA '), ('SQ', 'Grain'), ('SS', 'SS '), ('TC', 'TC '), ('TMAX', 'TMAX '), ('TMIN', 'TMIN '), ('TOXCHEM', 'TOXCHEM '), ('TS', 'Orage'), ('TSUNAMI', 'TSUNAMI '), ('VA', 'VA '), ('VEHICLE_RIME', 'VEHICLE_RIME '), ('VENT', 'VENT '), ('VENT_MOY', 'VENT_MOY')], max_length=20)),
                ('seuil', models.FloatField(blank=True, null=True)),
                ('auto', models.BooleanField(default=False)),
                ('pause', models.IntegerField(default=2)),
                ('scan', models.IntegerField(default=12)),
                ('profondeur', models.IntegerField(default=12)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configmaa', to='configurateur.station')),
            ],
            options={
                'ordering': ['station', 'type_maa', 'seuil'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='configmaas',
            field=models.ManyToManyField(blank=True, to='configurateur.ConfigMAA'),
        ),
        migrations.AddField(
            model_name='client',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='regions', to='configurateur.Region'),
        ),
        migrations.AddField(
            model_name='client',
            name='stations',
            field=models.ManyToManyField(blank=True, related_name='station', to='configurateur.Station'),
        ),
        migrations.AddConstraint(
            model_name='configmaa',
            constraint=models.UniqueConstraint(fields=('station', 'type_maa', 'seuil'), name='unique combo MAA par station'),
        ),
    ]
