# Generated by Django 3.2.10 on 2021-12-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurateur', '0002_remove_station_temp_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='inseeaero',
            field=models.CharField(default='1234567', max_length=7, verbose_name='INSEEaero'),
            preserve_default=False,
        ),
    ]
