# Generated by Django 3.2.10 on 2021-12-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurateur', '0003_station_inseeaero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='tag',
            field=models.TextField(max_length=40, unique=True, verbose_name='Tag région'),
        ),
    ]
