# Generated by Django 3.2.10 on 2021-12-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyseur', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envoimaa',
            options={'verbose_name': 'Envoi MAA', 'verbose_name_plural': 'Envois MAA'},
        ),
    ]
